version: "3"
services:
 url:
    image: csagan/lab1:lab2
    container_name: url_hash
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - bridge-network
 mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    networks:
      - bridge-network

networks:
 bridge-network:
    driver: bridge
